### PR TITLE
New overload for Socket.Recv

### PR DESCRIPTION
**Pull request by fholm**
Added an overload to the Socket.Recv method which has the signature `byte[] Recv(byte[] message, out int size, params SendRecvOpt[] flags)` to allow a `byte[]` to be supplied to the `Recv` function, and if it has enough space that buffer will be used instead of allocating a new `byte[]` constantly which causes a lot of pressure on the GC during high frequency messaging.

The supplied `message` parameter will only be used if two conditions are met: 
- It's not null
- It's `Length` property is larger then or equal to the size of the message

The size of the read message is also passed out through the `out int size` parameter so that in the case of using a `message` parameter which is larger then the message returned there is a way to find out how many bytes of the array that the message occupies.

### CODE REVIEW

**Comment by fholm** [comment]
I realized my copy of VS uses another formatting then the one in the clrzmq2 project, I apologize for the extra added changes which were just line-breaks before opening braces.

**Comment by jgoz** [comment]
This is excellent -- thank you for submitting this. I will probably merge it in before the weekend is over.

After seeing this request, your overload seems like an obvious one that should have been there from the start. It's very similar to the .Net Sockets API and will certainly help reduce GC pressure in projects with high messaging activity. 

Don't worry about the formatting -- this is an inherited codebase. The next version of the project will use standard C# style.

**Comment by fholm** [comment]
Ah, now my two new commits got added to this pull request also, this was not my intention. The RecvAll overload removes the need to allocate a new `Queue<byte[]>` object constantly, which I suppose is in the same spirit as the previous commit with the new Recv() overload.

The last commit modifies the `Recv(int timeout)` function to not stall the CPU constantly as this can freeze a one core systems (many VPS:es, etc.), but will also be more efficient on multi-core systems by not consuming one core constantly.

**Comment by fholm** [comment]
Also added two new overloads for Send: 

`Send(byte[] message, int startIndex, int length, params SendRecvOpt[] flags)`
`Send(byte[] message, int length, params SendRecvOpt[] flags)`

So it's possible to send a part of a byte array as a message, the reason for this is that usually in messaging applications the byte arrays are pre-allocated to the largest possible message size so there is no need to re-size or re-allocate buffers during runtime (as this stresses the GC), but most messages will not fill the whole byte array and the previous API would cause a bunch of null bytes or possibly garbage from previous messages (due to re-cycling the byte arrays) to be sent.

**Comment by jgoz** [comment]
Thanks Fredrik, I just merged your changes in. I made some minor formatting and wording changes, but left it as-is otherwise.

FYI, I will be renaming this repository today (removing the "2"), so you will need to update your remotes if you are making further enhancements.

Thanks for contributing! I'll be adding functional tests over the next week or two and I'll make sure your overloads get covered.

**Pull request merged**
