### PR TITLE
Small bug in the new Recv(int timeout) method

### PR DESCRIPTION
**Pull request by fholm**
Was a small bug in the changed `Recv(int timeout)` method, fixed in this commit.

### CODE REVIEW

**Comment by jgoz** [comment]
Yes, I noticed this issue last night while writing tests -- it's fixed in a local branch, but hasn't made it to master yet. I'll merge your fix in tonight.

Thanks!

**Comment by fholm** [comment]
Thanks for a quick reply, and sorry for the slight bug. Added the timeout > 1 test as an afterthought, suppose that's what I get for trying to be clever ;p

**Comment by jgoz** [comment]
No problem. The whole block is a nice trick for avoiding unnecessary context switches.

Now that I'm thinking about it, where did the values come from for the SpinWait duration and number of iterations? Are they standard for this particular pattern, or did you derive them yourself?

**Comment by fholm** [comment]
The values for SpinWait is something I've just derived after a lot of use, it's also the values that are used internally in the BCL by Microsoft most of the times. They tend to use a 50-100 (\* CPU count) for spin wait and 20 iterations, or something in that region

**Comment by fholm** [comment]
You can of course play around with the values, but I did some decent testing with different values (on both a CPU with HT and one without) and these seemed to give the lowest shredding of the CPU on both.

**Comment by jgoz** [comment]
That's good enough for me. I don't have a non-HT CPU available for testing, so I'll trust you blindly. :)

I'm sure you've used this more than a few times while optimizing IronJS.

**Pull request merged**
