### PR TITLE
Add support for ZMQ 3.2 context monitor

### PR DESCRIPTION
**Pull request by ievgent**
Some issues still not solved:
- no acceptance tests
- not tested under mono (EventDataFileDescriptorEntry.cs, ZmqMonitorFileDescriptorEventArgs.cs and LibZmq.Mono.cs)
- some events not properly worked, but it is not related to the .NET (see https://github.com/zeromq/zeromq3-x/pull/23 )

### CODE REVIEW

**Comment by jgoz** [comment]
Nice work! I really like this implementation. I'll do some in-depth review and try to write some tests for it in the next few days.

**Comment by ievgent** [comment]
It would be great.

**Comment by jgoz** [comment]
I took your implementation and made a few changes:
- Changed namespace to `ZeroMQ.Monitoring`
- Fixed a few spelling mistakes
- Added tests for events that can be triggered via C# code

The tests all pass with your zeromq3-x branch. Hopefully it will get merged in soon.

Thanks for your work on this!

**Comment by ievgent** [comment]
Thanks for your refactoring.

**Pull request closed without merging**
