### PR TITLE
Fix for bad pointer exception with LIBZMQ

### PR DESCRIPTION
**Pull request by ghost**
Wrong branch selected. Sorry this is my first time using github. Please cancel this request.

### CODE REVIEW

**Comment by jgoz** [comment]
Hi there,

It looks like you're opening a pull request against the 2.2 branch, but you've targeted the master branch. Can you please open a new request against the correct branch?

Alternately, please log an issue and I will fix both the 2.2 branch and the master branch, as it sounds like both will be affected.

One question first: how is one socket simultaneously sending and receiving a message? Are you sharing a single socket between multiple threads?

**Comment by ghost** [comment]
Hi Jgoz,
First thanks for the C# implementation, its saved me a ton of time writing my own. Second my apologies for selecting the wrong branch. A question, as I'm new to github, if I'm just submitting a change do I need to create a new branch or is submitting a log issue enough?

As to answer your question I'm using the Pair pattern with a socket, which allows for simultaneous bi-directional communication.

Thanks again,
Aaron

**Comment by jgoz** [comment]
> A question, as I'm new to github, if I'm just submitting a change do I need to create a new branch or is submitting a log issue enough?

It's generally preferred to make pull requests from a new branch specific to the fix you are working on. GitHub will do this automatically for you if you do a "Fork and Edit" operation (your branch in this case was called `patch-1`). If you manually forked the repository and submitted a pull request from there, you'd have to also manually create your own branch.

The reason this is preferred is because pull requests automatically get updated as you add commits to the source branch, so you can accidentally end up mixing different fixes together.

Also, GH will automatically create an Issue for each pull request you submit, so you don't _have to_ create a separate issue if you already have a fix. It's enough just to describe the issue in the pull request itself.

Thanks for contributing!

**Comment by ghost** [comment]
Awesome I appreciate the explanation. Thank you for the information. Also your welcome for the bug fix.

**Pull request closed without merging**
