### PR TITLE
AnyCPU Build Platform Support

### PR DESCRIPTION
**Pull request by jgoz**
This set of changes enables the 'AnyCPU' build platform.

It uses dynamic library loading on both Windows and Posix/Mono. On application start, it finds a suitable libzmq shared lib for the current platform, which can be x86, x64 or AnyCPU. Upon successfully loading the library using `LoadLibrary` or `dlopen`, it loads the libzmq procedures as delegates on the ZMQ.C static class using `GetProcAddress` or `dlsym`.

The resulting API is unchanged from before. All preprocessor conditionals involving `x86` or `x64` have been removed, as they are no longer necessary. In addition, the `ReadSizeT`/`WriteSizeT` methods were changed to swap between 32- and 64-bit integers at runtime depending on `IntPtr.Size`.

The advantage of AnyCPU is that clrzmq can be deployed to a mix of 32- and 64-bit machines without issues; it will default to using the native platform of the deployed machine. This is especially useful on a heterogeneous cluster of Linux machines where the package manager installation of libzmq defaults to the native platform.

The existing x86 and x64 platform targets are still available and useful if one or the other is required. For example, to deploy a 32-bit assembly on a 64-bit machine, clrzmq must target the x86 platform at compile time.

### CODE REVIEW

**Comment by jgoz** [comment]
One thing I just noticed -- the set of commits has been bloated due to inconsistent line endings in some of the files. Hopefully this doesn't create too many problems.

**Comment by Guthur** [comment]
Cheers for this, and fixing the line endings.

I'm going to just take a day or two to run a few tests to double check before merging. I'm sure it's fine though

**Comment by a-h** [comment]
I think that it could be better to add additional options for loading the external DLLs to allow Web applications to use the library more easily:

```
    static C()
    {
        string[] libCandidates = Is64BitProcess()
                                ? new[] { "libzmq64", "libzmq32", "libzmq" }
                                : new[] { "libzmq32", "libzmq" };

        string basePath = AppDomain.CurrentDomain.BaseDirectory;

        var candidates = new List<string>();

        // Create full paths to the DLLs.
        foreach (string candidate in libCandidates)
        {
            // Probe the base path first.
            candidates.Add(basePath + Path.DirectorySeparatorChar + candidate + ".dll");
            // See if there's a bin directory (this code could be running in an ASP.Net Web Application).
            candidates.Add(basePath + Path.DirectorySeparatorChar + "bin" + Path.DirectorySeparatorChar + candidate + ".dll");
        }

        ZmqLib = new UnmanagedLibrary(candidates.ToArray());
        AssignDelegates();
    }
```

**Comment by jgoz** [comment]
Something like this should work as long as users are aware that they need to put libzmq in their Bin directory -- it won't get copied there automatically.

I'd also modify your snippet to include the pathless libzmq candidates first, just in case they are installed on a system path somewhere. I'll test this out tonight or tomorrow and add to this pull request if it works as expected.

Another (heavy-handed) option might be to bundle the libzmq dlls with clrzmq.dll as embedded resources, then write them out to disk at run-time to either the bin directory or a temporary path, depending on permissions. That approach would reduce deployment requirements, but it would couple clrzmq with a specific version of libzmq and it would pollute the clrzmq codebase.

**Comment by rgl** [comment]
I've followed another route. In the latest nuget packages (clrzmq2 and clrzmq2-x64), I'm automatically including the libzmq.dll file in the project, I'm also setting it up to be copied to the output folder.

**Comment by danielcrenna** [comment]
Any chance this can still be included? I know you have x86 / x64 builds on NuGet, but we're having serious issues with choosing the x64 only build, since we have to run unit tests in 32bit mode due to limitations of Visual Studio. My particular project really needs an AnyCPU version, not just helpful inclusion of libzmq.dll...

**Comment by sustrik** [comment]
Hi guys, is this project still alive? There are no commits since May and there are multiple pull requests pending. I've tried to contact the maintainer, but got no response so far.

**Comment by jgoz** [comment]
It's alive in that a lot of people are using it in production and I'm sure any of us would be happy to take over maintenance duties. There are a few correctable problems with the project as-is, beyond the current queue of pull requests, but it's not insurmountable.

**Comment by sustrik** [comment]
jgoz: let's wait till next week, whether michael replies; if not, i can add you to the project maintainers

**Comment by jgoz** [comment]
I'm retracting this pull request. AnyCPU support will be added soon, but it will be made optional, likely as a separate build target & nuget package.

**Comment by danielcrenna** [comment]
Hey,

I'm using an AnyCPU version of the code in a production environment. My version is a custom one based largely off this fork though I made a few modifications as we do in fact run into stability problems on the machines we deploy to.

For the most part I'd declare this fork stable. I don't like that a) we get surprised by having to install the Visual Studio 2010 C++ Redistributable in order for the libzmq64/32 .dll's to work... I'm not saying this is a bad thing in general but just that it should be documented... b) the libzmq64/32 dlls have issues running in IIS. Specifically, the w3wp.exe has a hard time letting go of socket connections even when you are careful about context sharing, disposing, using Recv with the no blocking option set, etc. In addition to that, IIS can't "find" the DLLs in the BIN directory like regular console and Windows Services applications do, so you have to manually drop them in C:\Windows or C:\Windows\System32, so there's another additional deployment detail to worry about.

Again, all things that can be documented for future users. Performance wise it's been nothing but a small miracle where I'm using it. My main reason for requiring AnyCPU is being able to run the socket tests in Visual Studio / ReSharper / Cassini all run in x86 and also simultaneously deploying the same code to x64 production machines.

Cheers,

Daniel

**Comment by jgoz** [comment]
Thanks Daniel. I'm glad you were eventually able to get it running. Just a couple questions for you:

What kind of modifications did you make to improve stability? Would they benefit others using clrzmq or are they specific to your environment?

To address your points:

a. You're right, this should be documented. I believe the default project settings for libzmq specify the `/MD` compile option, which dynamically links the C runtime (`msvcr100.dll`) and requires the redist package to be installed. If you change that option to `/MT`, it will statically link the C runtime and will not require the redist package. In the VS project settings, this option is under C/C++ -> Code Generation -> Runtime library.

b1. Are these hanging connections intermittent, or can you reproduce them reliably? It sounds like you're properly closing the sockets before closing the context, which is a common omission, so I'd like to try to reproduce this on my end if possible.

b2. IIS requires native libs loaded through LoadLibrary to be placed somewhere on the system path, unfortunately. I waded through blog posts as far back as 2004 trying to find a reliable way around it, but I was not able to. The only solution that seemed to work is the one I used on my experimental netzmq bindings. Basically, the native libraries get compiled into the .NET DLL as manifest resources and are then extracted to and explicitly loaded from a temporary system path in a static context. It's a major hack, but it works. I think it's a fairly common technique, unfortunately.

Anyway, thanks again for the feedback -- I'm glad it's working for you in some capacity. Documentation is sorely lacking on these bindings and it's something I intend to change very soon.

**Pull request closed without merging**
