### PR TITLE
Some new socket options.

### PR DESCRIPTION
**Pull request by ievgent**
I'm have done TCP socket options, but have no idea how to test. It has no effect on Windows.

### CODE REVIEW

**Comment by jgoz** [comment]
This looks great; nice work. I'll see if I can come up with some test cases for the TCP socket options and then merge this in. It should be included into the `3.0.0-beta2` release.

**Comment by ievgent** [comment]
TCP socket options is missing here, i will push it in the separate request.

**Comment by jgoz** [comment]
Oh ok. In that case I'll just review these changes.

It looks like this pull request is coming from your `master` branch. You may want to create separate branches for future pull requests. Pull requests automatically get updated as you add commits to a branch.

**Comment by ievgent** [comment]
okey.

**Pull request closed without merging**
